export const services = [
  {
    id: 'strategy',
    number: '01',
    title: 'Product Strategy',
    summary: 'Turn an early idea into a practical plan for a focused, buildable product.',
    items: ['MVP definition', 'Feature prioritization', 'Product roadmaps', 'Technical guidance', 'Budget and timeline planning'],
  },
  {
    id: 'development',
    number: '02',
    title: 'App Development',
    summary: 'Build a polished product that works across the platforms your audience uses.',
    items: ['iOS applications', 'Android applications', 'Web applications', 'Cross-platform development', 'Backend integrations'],
  },
  {
    id: 'design',
    number: '03',
    title: 'Product Design',
    summary: 'Create an interface that is clear, useful, responsive, and enjoyable to use.',
    items: ['User experience', 'Interface design', 'User flows', 'Interactive prototypes', 'Product testing'],
  },
  {
    id: 'launch',
    number: '04',
    title: 'Launch & Growth',
    summary: 'Prepare your product for real users, measure what matters, and improve it over time.',
    items: ['App Store publishing', 'Google Play publishing', 'Analytics planning', 'Privacy guidance', 'Ongoing support'],
  },
]

export const projects = [
  {
    id: 'gridded',
    slug: 'gridded',
    name: 'Gridded',
    category: 'Game & Mobile Product',
    status: 'Public Beta',
    tagline: 'Find the words. Travel the world. Race together.',
    description: 'A premium word-grid experience built around daily destinations, relaxing progression, story-driven adventures, and competitive multiplayer.',
    problem: 'Traditional word-search games can feel repetitive, disconnected, and visually flat. Gridded was created to make the familiar word-grid format feel like a polished journey players want to return to.',
    solution: 'The product combines daily challenges, destination-based progression, game modes with distinct mechanics, player accounts, multiplayer competition, audio, haptics, and mobile publishing into one cohesive experience.',
    story: 'Gridded began as a focused word-grid prototype and evolved through repeated testing into a broader cross-platform game with daily play, progression, narrative modes, and multiplayer systems.',
    features: ['Daily destination challenges', 'Marathon progression', 'Quest Adventures', 'Competitive and cooperative multiplayer', 'Player profiles and progress', 'Audio, haptics, ads, and rewards'],
    platforms: ['Web', 'Android', 'iOS development'],
    demonstrates: ['Cross-platform application development', 'Mobile game systems', 'Multiplayer and player accounts', 'Monetization and rewarded ads', 'App-store preparation', 'Iterative product design'],
    primaryLabel: 'Play Gridded',
    primaryHref: 'https://playgridded.com',
    accent: 'violet',
    button: 'bg-violet-300 text-slate-950 hover:bg-violet-200',
    glow: 'bg-[radial-gradient(circle_at_30%_25%,rgba(139,92,246,.24),transparent_38%),radial-gradient(circle_at_80%_80%,rgba(14,165,233,.16),transparent_34%)]',
    images: ['/images/gridded/home.png', '/images/gridded/puzzle.png', '/images/gridded/marathon.png', '/images/gridded/multiplayer.png', '/images/gridded/quest.png'],
  },
  {
    id: 'swipethevote',
    slug: 'swipethevote',
    name: 'SwipeTheVote',
    category: 'Civic Technology',
    status: 'Live Product',
    tagline: 'Explore issues. Understand your civic landscape.',
    description: 'An independent civic education platform that helps people explore government actions through interactive questions, verified source links, saved civic history, and alignment tools.',
    problem: 'Civic information is often fragmented, difficult to understand, and disconnected from the decisions people encounter in their own communities.',
    solution: 'SwipeTheVote organizes civic exploration into an approachable product with location-aware discovery, interactive questions, official sources, saved history, and alignment results.',
    story: 'The platform was designed to help users move beyond campaign messaging and explore the issues, institutions, and public officials connected to their own civic landscape.',
    features: ['ZIP-based civic discovery', 'Local, state, and national exploration', 'Interactive issue questions', 'Official source links', 'Saved civic history', 'Alignment and match results'],
    platforms: ['Responsive web application'],
    demonstrates: ['Civic and nonprofit technology', 'Privacy-conscious product design', 'Complex information made approachable', 'Personalized data experiences', 'Responsive interface systems', 'Product analytics thinking'],
    primaryLabel: 'View Project',
    primaryHref: '/work/swipethevote',
    accent: 'rose',
    button: 'bg-rose-300 text-slate-950 hover:bg-rose-200',
    glow: 'bg-[radial-gradient(circle_at_25%_20%,rgba(244,63,94,.2),transparent_38%),radial-gradient(circle_at_85%_75%,rgba(59,130,246,.15),transparent_36%)]',
    images: ['/images/swipethevote/home.png', '/images/swipethevote/question.png', '/images/swipethevote/alignment.png', '/images/swipethevote/officials.png', '/images/swipethevote/matches.png'],
    note: 'A civic education project of SwipeTheVote Foundation Inc.',
  },
  {
    id: 'perfect5',
    slug: 'perfect-5',
    name: 'Perfect 5',
    category: 'Sports Strategy',
    status: 'Playable Prototype',
    tagline: 'Build five. Win possessions. Reach 21.',
    description: 'A fast basketball strategy duel where players build a five-card roster under a daily budget and compete through possession-based matchups.',
    problem: 'Fantasy basketball products can require long seasons, deep statistical knowledge, and a large time commitment before a player gets a satisfying result.',
    solution: 'Perfect 5 compresses roster strategy into quick daily decisions: build a five-player lineup under budget, compare player strengths, and play a first-to-21 possession battle.',
    story: 'Perfect 5 was built as a rapid product prototype to test whether roster construction and basketball possessions could form a lightweight, repeatable strategy game.',
    features: ['Daily player pools', 'Budget-based roster building', 'Offensive and defensive attributes', 'CPU matchups', 'Possession-based scoring', 'Multiplayer foundation'],
    platforms: ['Responsive web prototype'],
    demonstrates: ['Rapid product prototyping', 'Sports game mechanics', 'Daily content systems', 'Roster and budget logic', 'Turn-based gameplay', 'Responsive application design'],
    primaryLabel: 'View Project',
    primaryHref: '/work/perfect-5',
    accent: 'amber',
    button: 'bg-amber-300 text-slate-950 hover:bg-amber-200',
    glow: 'bg-[radial-gradient(circle_at_25%_20%,rgba(250,204,21,.16),transparent_36%),radial-gradient(circle_at_85%_75%,rgba(96,165,250,.17),transparent_38%)]',
    images: ['/images/perfect5/home.png', '/images/perfect5/build.png', '/images/perfect5/versus.png', '/images/perfect5/results.png'],
  },
]

export const processSteps = [
  { number: '01', title: 'Strategy Session', text: 'We discuss the idea, audience, goals, constraints, and current stage.' },
  { number: '02', title: 'Product Roadmap', text: 'We define the MVP, feature priorities, technical direction, and recommended next steps.' },
  { number: '03', title: 'Proposal & Plan', text: 'You receive a clear scope, deliverables, timeline, milestones, and project price.' },
  { number: '04', title: 'Design & Development', text: 'The product is designed, built, reviewed, and tested in practical stages.' },
  { number: '05', title: 'Launch', text: 'We prepare the website, stores, analytics, privacy requirements, and release.' },
  { number: '06', title: 'Grow', text: 'Feedback and product data guide improvements, support, and future releases.' },
]

export const pricing = [
  { title: 'Product Strategy Session', price: '$100', text: 'A focused 60-minute session plus a written next-steps summary.' },
  { title: 'Prototype & Product Planning', price: 'Starting around $1,500', text: 'Product definition, user flows, interface concepts, and interactive prototypes.' },
  { title: 'Focused MVP Development', price: 'Starting around $5,000', text: 'Tightly scoped first versions built to validate an idea or launch an essential experience.' },
  { title: 'Custom Applications', price: 'Scope-based pricing', text: 'For larger products, complex data, payments, accounts, multiplayer, or multiple platforms.' },
]
